[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "caddy"]

[phases.build]
cmds = []

[start]
cmd = "php-fpm82 & caddy run --config /app/Caddyfile"